# Generated by Django 3.0.3 on 2020-03-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningDomain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('position', models.PositiveSmallIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'curricula_learning_domain',
                'permissions': (('view_learningdomain', 'View learning domain'), ('list_learningdomain', 'List learning domain'), ('view_learningdomain_test', 'View learning domain test'), ('list_learningdomain_test', 'List learning domain test'), ('add_learningdomain_test', 'Attach learning domain test'), ('delete_learningdomain_test', 'Detach learning domain test')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LearningLecture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('summary', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('position', models.PositiveSmallIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'curricula_learning_lecture',
                'permissions': (('view_learninglecture', 'View learning lecture'), ('list_learninglecture', 'List learning lecture'), ('view_learninglecture_test', 'View learning lecture test'), ('add_learninglecture_test', 'Attach learning lecture test'), ('delete_learninglecture_test', 'Detach learning lecture test')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LearningLectureLiveScribe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'curricula_learning_lecture_livescribe',
                'permissions': (('view_learninglecturelivescribe', 'View learning lecture livescribe'), ('list_learninglecturelivescribe', 'List learning lecture livescribe')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LearningLectureStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lecture_status', models.PositiveSmallIntegerField(default=0)),
                ('practice_status', models.PositiveSmallIntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'curricula_learning_lecture_stat',
                'permissions': (('view_learninglecturestat', 'View learning lecture stat'), ('list_learninglecturestat', 'List learning lecture stat')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LearningLectureText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'curricula_learning_lecture_text',
                'permissions': (('view_learninglecturetext', 'View learning lecture text'), ('list_learninglecturetext', 'List learning lecture text')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LearningLectureVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'curricula_learning_lecture_video',
                'permissions': (('view_learninglecturevideo', 'View learning lecture video'), ('list_learninglecturevideo', 'List learning lecture video')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LearningLectureYoutube',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('file', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'curricula_learning_lecture_youtube',
                'permissions': (('view_learninglectureyoutube', 'View learning lecture youtube'), ('list_learninglectureyoutube', 'List learning lecture youtube')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LearningLesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('active', models.PositiveSmallIntegerField()),
                ('public', models.PositiveSmallIntegerField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'curricula_learning_lesson',
                'permissions': (('view_learninglesson', 'View learning lesson'), ('list_learnin glesson', 'List learning lesson')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LearningSubject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('position', models.PositiveSmallIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'curricula_learning_subject',
                'permissions': (('view_learningsubject', 'View learning subject'), ('list_learningsubject', 'List learning subject'), ('view_learningsubject_test', 'View learning subject test'), ('list_learningsubject_test', 'List learning subject test'), ('add_learningsubject_test', 'Attach learning subject test'), ('delete_learningsubject_test', 'Detach learning subject test')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LearningTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'db_table': 'curricula_learning_tag',
                'permissions': (('view_learningtag', 'View learnimg tag'), ('list_learningtag', 'List learning tag')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LearningTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('position', models.PositiveSmallIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'curricula_learning_test',
                'permissions': (('view_learningtest', 'View learning test'), ('list_learningtest', 'List learning test')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('position', models.PositiveSmallIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('component', models.ManyToManyField(related_name='unit_component', to='components.Component')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curricula.LearningDomain')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', related_query_name='unit', to='curricula.LearningLesson')),
            ],
            options={
                'db_table': 'curricula_learning_unit',
                'permissions': (('view_learningunit', 'View learning unit'), ('list_learningunit', 'List learning unit'), ('view_learningunit_test', 'View learning unit test'), ('list_learningunit_test', 'List learning unit test'), ('add_learningunit_test', 'Attach learning unit test'), ('delete_learningunit_test', 'Detach learning unit test')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='LearningTestUnique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('learning_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curricula.LearningTest')),
            ],
            options={
                'db_table': 'curricula_learning_test_unique',
                'permissions': (('view_learningtestunique', 'View learning test unique'), ('list_learningtestunique', 'List learning test unique')),
                'default_permissions': (),
            },
        ),
    ]
