# Generated by Django 3.0.3 on 2020-05-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0002_auto_20200303_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learninglecture',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='learninglecture',
            name='object_id',
        ),
    ]
