# Generated by Django 3.0.3 on 2020-05-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0004_auto_20200501_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learninglesson',
            options={'default_permissions': (), 'permissions': (('view_learninglesson', 'View learning lesson'), ('list_learninglesson', 'List learning lesson'))},
        ),
    ]
