# Generated by Django 3.0.3 on 2020-06-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0006_auto_20200604_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningtestunique',
            name='learning_test',
        ),
        migrations.RemoveField(
            model_name='learningtestunique',
            name='user',
        ),
        migrations.DeleteModel(
            name='LearningTest',
        ),
        migrations.DeleteModel(
            name='LearningTestUnique',
        ),
    ]
