# Generated by Django 3.0.3 on 2020-06-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200531_2007'),
        ('curricula', '0007_auto_20200604_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninglecture',
            name='lesson',
            field=models.ManyToManyField(related_name='lecture_lesson', to='companies.SchoolLessonTeacher'),
        ),
    ]
