# Generated by Django 3.0.3 on 2020-03-03 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0002_auto_20200303_2121'),
        ('library', '0002_media_publisher'),
        ('tests', '0001_initial'),
        ('publishers', '0003_auto_20200303_2121'),
        ('questions', '0001_initial'),
        ('educategories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionanswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_question_answer_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionuniquestat',
            name='question_unique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_unique_stat_question_unique', to='questions.QuestionUnique'),
        ),
        migrations.AddField(
            model_name='questionuniquestat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_unique_stat_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.Exam'),
        ),
        migrations.AddField(
            model_name='questionexam',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
        migrations.AddField(
            model_name='questionanswerstat',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_stat_question', to='questions.Question'),
        ),
        migrations.AddField(
            model_name='questionanswerstat',
            name='question_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_stat_question_answer', to='questions.QuestionAnswer'),
        ),
        migrations.AddField(
            model_name='questionanswerstat',
            name='test_unique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_stat_test_unique', to='tests.TestUnique'),
        ),
        migrations.AddField(
            model_name='questionanswerstat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_stat_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='component',
            field=models.ManyToManyField(related_name='ccc', through='components.ComponentAnswer', to='components.Component'),
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to='questions.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='book',
            field=models.ManyToManyField(related_name='question_book', to='publishers.Book'),
        ),
        migrations.AddField(
            model_name='question',
            name='component',
            field=models.ManyToManyField(related_name='question_components', to='components.Component'),
        ),
        migrations.AddField(
            model_name='question',
            name='edu_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_edu_category', to='educategories.EduCategory'),
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ManyToManyField(related_name='question_exam', through='questions.QuestionExam', to='library.Exam'),
        ),
        migrations.AddField(
            model_name='question',
            name='publisher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_publisher', to='publishers.Publisher'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_unique',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_question_unique', to='questions.QuestionUnique'),
        ),
    ]
