# Generated by Django 3.0.3 on 2020-04-25 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20200423_2322'),
        ('questions', '0002_auto_20200303_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='questionanswerstat',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_stats', to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='questionanswerstat',
            name='question_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='questions.QuestionAnswer'),
        ),
        migrations.AlterField(
            model_name='questionanswerstat',
            name='test_unique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_unique_stats', to='tests.TestUnique'),
        ),
    ]
