# Generated by Django 3.0.3 on 2020-04-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200425_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswerstat',
            name='answer_count',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
