# Generated by Django 3.0.3 on 2020-05-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_questionanswerstat_answer_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionuniquestat',
            name='answers',
        ),
    ]
