# Generated by Django 3.0.3 on 2020-05-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_questionuniquestat_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionuniquestat',
            name='solved',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
