# Generated by Django 3.0.3 on 2020-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_questionuniquestat_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionuniquestat',
            name='repeat',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
