from .condition import Condition
from .department import Department
from .discount import Discount
from .faculty import Faculty
from .language import Language
from .new import New
from .property import Property
from .section import Section
from .tag import Tag
from .university_type import UniversityType
from .university import University
