from .condition import ConditionSerializer
from .department import DepartmentSerializer
from .discount import DiscountSerializer
from .faculty import FacultySerializer
from .language import LanguageSerializer
from .new import NewSerializer
from .property import PropertySerializer
from .section import SectionSerializer
from .tag import TagSerializer
from .university import UniversitySerializer
from .university_type import UniversityTypeSerializer
