# Generated by Django 3.0.3 on 2020-03-03 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('publishers', '0002_source_question'),
        ('tests', '0001_initial'),
        ('curricula', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schooltest',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.School'),
        ),
        migrations.AddField(
            model_name='schooltest',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test'),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.School'),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolstudent',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.School'),
        ),
        migrations.AddField(
            model_name='schoolstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolmanager',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolmanager',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.School'),
        ),
        migrations.AddField(
            model_name='schoollessonteacher',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Lesson'),
        ),
        migrations.AddField(
            model_name='schoollessonteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.SchoolTeacher'),
        ),
        migrations.AddField(
            model_name='schoolbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.Book'),
        ),
        migrations.AddField(
            model_name='schoolbook',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.School'),
        ),
        migrations.AddField(
            model_name='school',
            name='book',
            field=models.ManyToManyField(related_name='school_books', through='companies.SchoolBook', to='publishers.Book'),
        ),
        migrations.AddField(
            model_name='school',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_group', to='companies.CompanyGroup'),
        ),
        migrations.AddField(
            model_name='school',
            name='lesson',
            field=models.ManyToManyField(related_name='school_curricula', through='companies.Lesson', to='curricula.LearningLesson'),
        ),
        migrations.AddField(
            model_name='school',
            name='manager',
            field=models.ManyToManyField(related_name='school_managers', through='companies.SchoolManager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='student',
            field=models.ManyToManyField(related_name='school_students', through='companies.SchoolStudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='teacher',
            field=models.ManyToManyField(related_name='school_teachers', through='companies.SchoolTeacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='test',
            field=models.ManyToManyField(related_name='school_tests', through='companies.SchoolTest', to='tests.Test'),
        ),
        migrations.AddField(
            model_name='school',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_type', to='companies.SchoolType'),
        ),
        migrations.AddField(
            model_name='school',
            name='user',
            field=models.ManyToManyField(related_name='school_users', through='companies.SchoolUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lesson',
            name='curricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curricula.LearningLesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_teacher',
            field=models.ManyToManyField(related_name='school_lesson_teacher', through='companies.SchoolLessonTeacher', to='companies.SchoolTeacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_school', to='companies.School'),
        ),
        migrations.AddField(
            model_name='companygroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroomteacher',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Classroom'),
        ),
        migrations.AddField(
            model_name='classroomteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroomstudent',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Classroom'),
        ),
        migrations.AddField(
            model_name='classroomstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroomlesson',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Classroom'),
        ),
        migrations.AddField(
            model_name='classroomlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.SchoolLessonTeacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='lesson',
            field=models.ManyToManyField(related_name='classroom_lessons', through='companies.ClassroomLesson', to='companies.SchoolLessonTeacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.School'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='student',
            field=models.ManyToManyField(related_name='classroom_students', through='companies.ClassroomStudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ManyToManyField(related_name='classroom_teachers', through='companies.ClassroomTeacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
