# Generated by Django 3.0.3 on 2020-03-17 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0003_auto_20200303_2121'),
        ('companies', '0002_auto_20200303_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollessonteacher',
            name='publisher',
            field=models.ForeignKey(default=102, on_delete=django.db.models.deletion.CASCADE, to='publishers.Publisher'),
            preserve_default=False,
        ),
    ]
