# Generated by Django 3.0.3 on 2020-05-20 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_schoollessonteacher_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'default_permissions': (), 'permissions': (('super_classroom', 'All access for classroom'), ('view_classroom', 'View Classroom'), ('add_classroom', 'Add Classroom'), ('change_classroom', 'Update Classroom'), ('delete_classroom', 'Remove Classroom'), ('list_classrooms', 'List Classroom'))},
        ),
        migrations.AlterModelOptions(
            name='classroomlesson',
            options={'default_permissions': (), 'permissions': (('add_classroom_lesson', 'Attach Lesson to Classroom '), ('delete_classroom_lesson', 'Detach Lesson From Classroom'), ('change_classroom_lesson', 'Change Classroom Lesson'), ('view_classroom_lesson', 'View Classroom Lesson'), ('list_classroom_lessons', 'List Classroom Lesson'))},
        ),
        migrations.AlterModelOptions(
            name='classroomstudent',
            options={'default_permissions': (), 'permissions': (('list_classroom_students', 'List Classroom Students'), ('add_classroom_student', 'Attach Student to Classroom'), ('delete_classroom_student', 'Detach Student From Classroom'), ('view_classroom_student', 'View Classroom Student'))},
        ),
        migrations.AlterModelOptions(
            name='classroomteacher',
            options={'default_permissions': (), 'permissions': (('list_classroom_teachers', 'List Classroom Teachers'), ('add_classroom_teacher', 'Attach Teacher to Classroom'), ('delete_classroom_teacher', 'Detach Teacher From Classroom'), ('view_classroom_teacher', 'View Classroom Teacher'))},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'default_permissions': (), 'permissions': (('super_school', 'Super school'), ('list_schools', 'List school'), ('view_school', 'View school'), ('add_school', 'Add school'), ('change_school', 'Update school'), ('update_school', 'Update school'), ('delete_school', 'Delete school'), ('list_school_classrooms', 'View school classroom list'), ('list_school_lessons', 'List school lessons'), ('update_school_roles', 'Update school roles'))},
        ),
        migrations.AlterModelOptions(
            name='schoollessonteacher',
            options={'default_permissions': (), 'permissions': (('list_school_lesson_teachers', 'List school lesson teachers'), ('filter_school_lesson_teachers', 'List school lesson teachers'))},
        ),
        migrations.AlterModelOptions(
            name='schoolmanager',
            options={'default_permissions': (), 'permissions': (('add_school_manager', 'Attach manager to school'), ('delete_school_manager', 'Detach manager from school'), ('list_school_managers', 'List school managers'))},
        ),
        migrations.AlterModelOptions(
            name='schoolstudent',
            options={'default_permissions': (), 'permissions': (('add_school_student', 'Attach student to school'), ('delete_school_student', 'Detach student from school'), ('list_school_students', 'List school students'))},
        ),
        migrations.AlterModelOptions(
            name='schoolteacher',
            options={'default_permissions': (), 'permissions': (('add_school_teacher', 'Attach teacher to school'), ('delete_school_teacher', 'Detach teacher from school'), ('list_school_teachers', 'List school teachers'))},
        ),
        migrations.AlterModelOptions(
            name='schooltest',
            options={'default_permissions': (), 'permissions': (('list_school_tests', 'List school tests'),)},
        ),
        migrations.AlterModelOptions(
            name='schooluser',
            options={'default_permissions': (), 'permissions': (('add_school_user', 'Attach user to school'), ('delete_school_user', 'Detach user from school'), ('list_school_users', 'List school users'))},
        ),
    ]
