# Generated by Django 3.0.3 on 2020-05-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_auto_20200521_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'default_permissions': (), 'permissions': (('super_lesson', 'All lesson'), ('add_lesson', 'Add lesson'), ('change_lesson', 'Update lesson'), ('delete_lesson', 'Delete lesson'), ('list_lessons', 'List lesson'), ('view_lesson', 'View lesson'), ('attach_lesson_teacher', 'Add lesson teacher'), ('detach_lesson_teacher', 'Detach lesson teacher'), ('update_lesson_teacher', 'Update lesson teacher'), ('list_lesson_teacher', 'List lesson teachers'))},
        ),
        migrations.AddField(
            model_name='classroom',
            name='type',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
