# Generated by Django 3.0.3 on 2020-03-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('level', models.SmallIntegerField(default=1)),
                ('active', models.SmallIntegerField(default=1)),
                ('group', models.SmallIntegerField(default=0)),
                ('seconds', models.SmallIntegerField(default=150)),
                ('file', models.TextField(blank=True, default=None, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'components_component',
                'permissions': (('super_component', ''), ('view_component', ''), ('add_component', ''), ('change_component', ''), ('delete_component', ''), ('user_detail_component', ''), ('search_component', ''), ('parents_component', '')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ComponentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_ok', models.SmallIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'components_component_question_answer',
                'permissions': (('view_componentanswer', 'View component answer'), ('list_componentanswer', 'List component answer')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ComponentAnswerStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_is_true', models.SmallIntegerField()),
                ('answer_is_empty', models.SmallIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'components_component_answer_stat',
                'permissions': (('view_componentanswerstat', 'View component answer stat'), ('list_componentanswerstat', 'List component answer stat')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ComponentRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'components_component_component',
            },
        ),
        migrations.CreateModel(
            name='ComponentStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('component_status', models.SmallIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'components_component_stat',
                'permissions': (('view_componentstat', 'View component stat'), ('list_componentstat', 'List component stat')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ComponentStatusChange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('old_status', models.SmallIntegerField()),
                ('new_status', models.SmallIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_status_change_component', to='components.Component')),
            ],
            options={
                'db_table': 'components_component_status_change',
                'permissions': (('view_componentstatuschange', 'View component status change'), ('list_componentstatuschange', 'List component status change')),
                'default_permissions': (),
            },
        ),
    ]
