# Generated by Django 3.0.3 on 2020-03-03 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        ('questions', '0001_initial'),
        ('educategories', '0001_initial'),
        ('components', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='componentstatuschange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_status_change_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='componentstat',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_stat_component', to='components.Component'),
        ),
        migrations.AddField(
            model_name='componentstat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_stat_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='componentrelationship',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_source', to='components.Component'),
        ),
        migrations.AddField(
            model_name='componentrelationship',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_target', to='components.Component'),
        ),
        migrations.AddField(
            model_name='componentanswerstat',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_answer_stat_component', to='components.Component'),
        ),
        migrations.AddField(
            model_name='componentanswerstat',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_answer_stat_question', to='questions.Question'),
        ),
        migrations.AddField(
            model_name='componentanswerstat',
            name='test_unique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_answer_stat_test_unique', to='tests.TestUnique'),
        ),
        migrations.AddField(
            model_name='componentanswerstat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_answer_stat_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='componentanswer',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_answers', to='components.Component'),
        ),
        migrations.AddField(
            model_name='componentanswer',
            name='question_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.QuestionAnswer'),
        ),
        migrations.AddField(
            model_name='component',
            name='edu_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_category', to='educategories.EduCategory'),
        ),
        migrations.AddField(
            model_name='component',
            name='to_component',
            field=models.ManyToManyField(related_name='source_component', through='components.ComponentRelationship', to='components.Component'),
        ),
    ]
