# Generated by Django 3.0.3 on 2020-05-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_questionuniquestat_percent'),
        ('components', '0002_auto_20200303_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentstat',
            name='percent',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componentanswer',
            name='question_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_components', to='questions.QuestionAnswer'),
        ),
    ]
