# Generated by Django 3.0.3 on 2020-05-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_auto_20200507_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentstat',
            name='solved',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
