# Generated by Django 3.0.3 on 2020-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_componentstat_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentstat',
            name='repeat',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
