# Generated by Django 3.0.3 on 2020-05-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_componentstat_repeat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'default_permissions': (), 'permissions': (('super_component', ''), ('view_component', ''), ('add_component', ''), ('change_component', ''), ('delete_component', ''), ('list_components', ''), ('user_detail_component', ''), ('search_component', ''), ('parents_component', ''))},
        ),
    ]
