# Generated by Django 3.0.3 on 2020-03-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'permissions': (('view_report', 'View test report'), ('list_report', 'List test report')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'tests_report_type',
                'permissions': (('view_reporttype', 'View test report type'), ('list_reporttype', 'List test report type')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('test_seconds', models.SmallIntegerField()),
                ('test_start', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('active', models.SmallIntegerField(default=1)),
                ('test_type_id', models.SmallIntegerField(default=1)),
            ],
            options={
                'permissions': (('view_test', 'View test'), ('list_test', 'List test'), ('view_test_questions', 'View test question'), ('list_test_questions', 'List test questions')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TestUnique',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('report', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_unique_test', to='tests.Test')),
            ],
            options={
                'db_table': 'tests_test_unique',
                'permissions': (('view_testunique', 'View test unique'), ('list_testunique', 'List test unique')),
                'default_permissions': (),
            },
        ),
    ]
