# Generated by Django 3.0.3 on 2020-03-03 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0002_auto_20200303_2121'),
        ('tests', '0001_initial'),
        ('publishers', '0003_auto_20200303_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educategories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testunique',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_unique_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='educategories.EduCategory'),
        ),
        migrations.AddField(
            model_name='test',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_publisher', to='publishers.Publisher'),
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='questions.Question'),
        ),
        migrations.AddField(
            model_name='reporttype',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_type_report', to='tests.Report'),
        ),
        migrations.AddField(
            model_name='reporttype',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_type_test', to='tests.Test'),
        ),
        migrations.AddField(
            model_name='report',
            name='types',
            field=models.ManyToManyField(through='tests.ReportType', to='tests.Test'),
        ),
    ]
