# Generated by Django 3.0.3 on 2020-04-25 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200425_2345'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0003_auto_20200423_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ('sort_order',)},
        ),
        migrations.AddField(
            model_name='testunique',
            name='test_result',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='questions.Question'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='tests.Test'),
        ),
        migrations.AlterField(
            model_name='testunique',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='tests.Test'),
        ),
        migrations.AlterField(
            model_name='testunique',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
