# Generated by Django 3.0.3 on 2020-06-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200531_2007'),
        ('tests', '0007_test_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='classroom',
        ),
        migrations.AddField(
            model_name='test',
            name='lesson',
            field=models.ManyToManyField(related_name='lesson_teacher', to='companies.SchoolLessonTeacher'),
        ),
    ]
