# Generated by Django 3.0.3 on 2020-03-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='question',
            field=models.ManyToManyField(related_name='source_questions', to='questions.Question'),
        ),
    ]
